import Head from "next/head";
import { useEffect, useState } from "react";

import Header from "@/components/Header";
import MainLayout from "@/components/MainLayout";
import SearchBar from "@/components/SearchBar";
import PokeContainer from "@/components/PokeContainer";
import PokeItems from "@/components/PokeItems";
import Pokemon from "@/components/Pokemon";
import PageNavigatorBar from "@/components/PageNavigatorBar";

export default function Home() {
  const [page, setPage] = useState(1);
  const [searchValue, setSearchValue] = useState("");
  const [searchResponse, setSearchResponse] = useState(null);

  useEffect(() => {
    const getPokeDataByName = async () => {
      try {
        const data = await fetch(
          `https://pokeapi.co/api/v2/pokemon/${searchValue}`
        );
        const jsonData = await data.json();
        setSearchResponse(jsonData);
      } catch (error) {
        if (error) {
          console.log(error);
        }
      }
    };

    if (searchValue === "") {
      setSearchResponse(null);
    } else {
      getPokeDataByName();
    }
  }, [searchValue]);

  return (
    <>
      <Head>
        <title>Next - PokéAPI</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <MainLayout>
        <SearchBar setValue={setSearchValue} />
        <PokeContainer>
          {searchResponse !== null ? (
            <Pokemon
              id={searchResponse.id}
              name={searchResponse.name}
              sprites={searchResponse.sprites}
              types={searchResponse.types}
            />
          ) : (
            <PokeItems pageNumber={page} />
          )}
        </PokeContainer>
        {searchValue === "" && <PageNavigatorBar page={page} setPage={setPage} />}
      </MainLayout>
    </>
  );
}
